name: flutter_study
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.14
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1


dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  pedantic_mono: any

flutter:
  uses-material-design: true
